proyecto_final/clothes/urls.py
from django.urls import path

from clothes.views import create_clothing, list_categories, list_and_buy, clothes_update, ClothesDeleteView

urlpatterns = [
    path('create/', create_clothing),
    path('list-categories/', list_categories), 
    path('list-clothes/', list_and_buy), 
    path('update-clothes/<int:pk>/', clothes_update),
    path('delete-clothes/<int:pk>/', ClothesDeleteView.as_view(), name= 'delete_clothes'),
    
    ]

proyecto_final/proyecto_final/urls.py
from django.contrib import admin
from django.urls import path, include
from proyecto_final.views import index, about_me
from proyecto_final.settings import MEDIA_ROOT, MEDIA_URL
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('about-me/', about_me),
    path('clothes/', include('clothes.urls')),
    path('users/', include('users.urls'))] + static(MEDIA_URL, document_root = MEDIA_ROOT)

proyecto_final/sales/urls.py
from django.urls import path



urlpatterns = []

proyecto_final/clothes/models.py
from django.db import models
from sales.models import Payment


class Gender (models.Model):
    genders = models.CharField(max_length=10, null=True, verbose_name= "Genero de la prenda")
    
    def __str__(self):
        return self.genders
    
    class Meta():
        db_table = "Genders"
        verbose_name = 'Gender'
        verbose_name_plural = 'Genders'

class Type_Clothing (models.Model):
    categories= models.CharField(max_length=30, verbose_name= "Categoria de la prenda")
    
    class Meta():
        db_table = "Type_of_clothing"
        verbose_name = 'Type of clothes'
        verbose_name_plural = 'Type of clothes'
        
    def __str__(self):
        return self.categories

class Clothes (models.Model):
    name = models.CharField(max_length=100, verbose_name= "Nombre de la prenda")
    seller_username = models.CharField(max_length=20, null= True, verbose_name= "Usuario del vendedor")
    price = models.FloatField(verbose_name= "Precio de la prenda")
    category = models.ForeignKey(Type_Clothing, null=True, blank=True, on_delete=models.CASCADE, verbose_name= "Tipo de prenda")
    gender = models.ForeignKey(Gender, null=True, blank=True, on_delete=models.CASCADE, verbose_name= "Genero de la prenda")
    brand = models.CharField(max_length=50, null=True, verbose_name= "Marca de la prenda")
    size = models.CharField(max_length=50, null=True, verbose_name= "Talle de la prenda")
    new_clothing = models.BooleanField (verbose_name= "Prenda nueva")
    payment = models.ForeignKey(Payment, null=True, blank=True, on_delete=models.CASCADE, verbose_name= "Medio de pago" )
    is_available = models.BooleanField(default=True)
    buyer_username = models.CharField (max_length=20, null = True, verbose_name= "Comprador")
    cloth_picture = models.ImageField(upload_to='clothes_images', null=True, blank=True)

    
    class Meta():
        db_table = "Clothes"
        verbose_name = 'Clothes'
        verbose_name_plural = 'Clothes'

    def __str__(self):
        return f'{self.name} de marca {self.brand} con un precio de {self.price}'
    
    def setUnavailable(self):
        self.is_available = False

proyecto_final/clothes/forms.py
from django import forms
from clothes.models import Gender, Type_Clothing, Clothes
from sales.models import Payment

    
class ClothesForm(forms.ModelForm):
    class Meta:
        model = Clothes
        fields = ['name', 'seller_username', 'price', 'category', 'size', 'brand', 'gender', 'new_clothing', 'cloth_picture']
        labels = { 'name': ('Nombre de la prenda:' ), 'seller_username': ('Usuario del vendedor'), 'price' : ('Precio:'), 'category' : ('Categoria de la prenda:'), 'size': ('Talle de la prenda'),  'brand' : ('Marca de la prenda:'), 'gender' : ('Para quien es la prenda?'), 'new_clothing' : ('La prenda es nueva?'), 'cloth_picture' : ('Sube una foto:') }
    
    
    
class UpdateCloth (forms.ModelForm):
    class Meta: 
        model = Clothes
        fields = ['price']
    
class ClothesCart(forms.Form):
    buyer = forms.CharField(max_length=100, label= 'Tu username: ')
    cloth = forms.IntegerField(widget= forms.HiddenInput, initial = 1)
    type_payment = forms.ModelChoiceField(queryset=Payment.objects.all(), label = 'Medio de pago: ')

proyecto_final/clothes/views.py
from django.shortcuts import render, redirect
from clothes.models import Clothes, Type_Clothing
from clothes.forms import ClothesCart, UpdateCloth, ClothesForm
from django.views.generic import DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import user_passes_test, login_required

@login_required
def create_clothing (request):
    if request.method == 'GET':
        context = {
            'form': ClothesForm()}
        return render(request,'clothes/create.html', context=context)
    
    elif request.method == 'POST':
        form = ClothesForm(request.POST, request.FILES)
        if form.is_valid():
            Clothes.objects.create(
                name=form.cleaned_data['name'],
                seller_username = form.cleaned_data['seller_username'],
                price=form.cleaned_data['price'],
                category = form.cleaned_data['category'],
                size = form.cleaned_data ['size'],
                brand = form.cleaned_data['brand'],
                gender = form.cleaned_data['gender'],
                new_clothing = form.cleaned_data['new_clothing'],
                cloth_picture = form.cleaned_data ['cloth_picture']
                
            )
            context = {
                'message': 'Genial! Tu prenda esta lista para su venta'
            }
            return render(request, 'clothes/create.html', context=context)
        else:
            context = {
                'form_errors': form.errors,
                'form': ClothesForm()
            }
            return render(request, 'clothes/create.html', context=context)
        

def list_categories(request):
    all_categories = Type_Clothing.objects.all()
    context = {
        'categories':all_categories
    }
    return render(request, 'clothes/list_categories.html', context=context)

def list_and_buy(request):
    if request.method == 'GET':
        if 'search' in request.GET:
            search = request.GET['search']
            clothes = Clothes.objects.filter(name__icontains=search)
        else:
            clothes = Clothes.objects.all()
        context = {
            'clothes':clothes,
            'form': ClothesCart(),
        }
        return render(request, 'clothes/list_clothes.html', context=context)
    else:
        form = ClothesCart(request.POST)
        if form.is_valid():
            cloth = Clothes.objects.get(id=form.cleaned_data['cloth'])
            cloth.buyer_username = form.cleaned_data['buyer']
            cloth.payment = form.cleaned_data['type_payment']
            cloth.setUnavailable()
            cloth.save()
            context = {
                'message': f'Gracias por añadir el producto a tu carrito de compras {cloth.buyer_username} ! En breve nos pondremos en contacto contigo mediante email para procesar el pago :)'
            }
            return render(request, 'sales/pay_order.html', context=context)
        else:
            context = {
                'form_errors': form.errors,
                'form': ClothesCart()
            }
            return render(request, 'sales/pay_order.html', context=context)

@user_passes_test((lambda u: u.is_superuser))
def clothes_update(request, pk):
    clothes = Clothes.objects.get(id=pk)
    if request.method == 'GET':
        context = {
            'form': UpdateCloth(
                initial={
                    'price': clothes.price
                }
            )
        }

        return render(request,'clothes/update_clothes.html', context=context)

    elif request.method == 'POST':
        form = UpdateCloth(request.POST)
        if form.is_valid():
            clothes.price = form.cleaned_data['price']
            clothes.save()
            
            context = {
                'message': 'Genial! El precio de la prenda ha sido actualizada correctamente'
            }
        else:
            context = {
                'form_errors': form.errors,
                'form': UpdateCloth()
            }
        return render(request, 'clothes/update_clothes.html', context=context)


class SuperUserRequiredMixin(LoginRequiredMixin, UserPassesTestMixin):
    
    def test_func(self):
        return self.request.user.is_superuser


class ClothesDeleteView(SuperUserRequiredMixin, DeleteView):
    model = Clothes
    template_name = 'clothes/delete_clothes.html'
    success_url = '/clothes/list-clothes/'

proyecto_final/templates/clothes/create.html
{% extends "base.html" %}

{% block title %}
Vende
{% endblock %}

{% block content %}
<br>
<h1><p style="margin-left: 10px;"> Vende las prendas que ya no uses! </h1></br></p>


{% if form %}

<form action="" method="POST" enctype="multipart/form-data" style="margin-left: 10px;">

    {% csrf_token %}

    <table>
        {{form.as_table}}
    </table>


    <input type="submit" value="Publica tu prenda">
    <br><br>
</form>
{% endif %}


{% if form_errors %}
<h2 style="color: red;">Errores:</h2>
{{form_errors}}
{% endif %}


{% if message %}
<div class="alert alert-success" role="alert">{{message}}</div>
{% endif %}

{% endblock %}

proyecto_final/templates/clothes/delete_clothes.html
{% extends 'base.html' %}

{% block title %}
    Borrado de producto
{% endblock %}

{% block content %}

    <h2> <p style="margin-left: 10px;">Borrar el producto</h2></p>
    <p style="margin-left: 10px;"> Seguro que desea eliminar el producto?</p>

    <form action="" method="POST" style="margin-left: 10px;">
        {% csrf_token %}
        <input type="submit" value="Si, borrar">
        <a href="/clothes/listado_clothes/" class="btn btn-primary"  style="background-color: #e08385; border: white;">Cancelar</a>
    <br><br>
    </form>


{% endblock %}

proyecto_final/templates/clothes/list_categories.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock %}

{% block content %}

<h1><br> <p style="margin-left: 10px;">Los tipos de prenda que tenemos disponibles</br></h1>

{% for category in categories %}

<br>
<div class="card" style="width: 18rem;"></br>
  <div class="card-body">
    <h5 class="card-title"><b>{{category}}</b></h5>
    {% if request.user.is_authenticated %}
    <a href="/clothes/list-clothes/" class="card-link" style="color:#e08385;">Comprar</a>
    <a href="/clothes/create/" class="card-link" style="color:#e08385;">Vender tus prendas</a>
    {% endif %}
  </div>
</div>
</p>
{% endfor %}

{% endblock %}

proyecto_final/templates/clothes/list_clothes.html
{% extends 'base.html' %}

{% block title %}
Listado de productos
{% endblock %}

{% block content %}

<h1><p style="margin-left: 10px;">Nuestras prendas disponibles!</h1></p>

{% if request.user.is_authenticated %}
<h2><br> Queres publicar tus prendas? </br></h2> <a href="/clothes/create/" class="btn btn-primary"
    style="background-color:#e08385; border: white;">Publicar</a>
{% endif %}


<h2><br><p style="margin-left: 10px;">Actualmente tenemos las siguientes prendas en stock:</br></h2>

{% for clothing in clothes %}

<div class="card" style="width: 18rem; justify-content: center; left: 450px; width: 400px;"></br>
    {% if clothing.cloth_picture.url != '' %}
    <img src="{{clothing.cloth_picture.url}}" class="img-fluid rounded-start" alt="Clothes_pictures"
        width="1000%" height="1000%">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title">{{clothing.name}}</h5>
        <p class="card-text">Su categoria es <b>{{clothing.category}}</b></p>
        <p class="card-text">Su talle es <b>{{clothing.size}}</b></p>
        <p class="card-text">Su marca es <b>{{clothing.brand}}</b></p>
        <p class="card-text">Su precio es <b>${{clothing.price}}</b></p>
        {% if clothing.new_clothing == True %}
        <p>La prenda es nueva</p>
        {% else %}
        <p>La prenda es usada</p>
        {% endif %}
        {% if clothing.is_available == True %}
        <p><b>La prenda esta disponible para su compra</b></p>

        <br>
        {% if request.user.is_authenticated %}
        <h5><u> Queres comprar la prenda?</u></h5>
        <form action="/clothes/list-clothes/" method="POST">
            {% csrf_token %}

            <p>Tu username para procesar la compra : {{form.buyer}}</p> 
            <p>Medio de pago: {{form.type_payment}}</p> 

            <input type="hidden" name="cloth" value="{{clothing.id}}" id="id_cloth">
            <input type="submit" class="btn btn-primary" style="background-color:#e08385; border: white; width: 220px; display: block; margin-left: auto; margin-right: auto;"
                value='Comprar'>
                
        </form>
        <br>
            {% if request.user.is_superuser %}
            <a href="/clothes/update-clothes/{{clothing.pk}}/" class="btn btn-primary"
                style="background-color:#e08385; border: white; width: 220px; display: block; margin-left: auto; margin-right: auto;">Actualizar precio</a>
            <a href="/clothes/delete-clothes/{{clothing.pk}}/" class="btn btn-primary"
                style="background-color: red; border: red; display: block; width: 220px; margin-left: auto; margin-right: auto;">Borrar</a>
            {% endif %}
        {% endif %}
        {% else %}
        <p>Lo sentimos! La prenda ya se vendió</p>
        {% endif %}
    </div>
</div>
<br><br>
{% endfor %}

{% endblock %}

proyecto_final/templates/clothes/update_clothes.html
{% extends 'base.html' %}

{% block title %}
    Actualización de la prenda
{% endblock %}

{% block content %}
    <h1><p style="margin-left: 10px;">Deseas actualizar el precio de la prenda anteriormente cargada?</p></h1>



    {% if form %}

        <form action="" method="POST" style="margin-left: 10px;">

            {% csrf_token %}

            <table>
                {{form.as_table}}
            </table>


            <input type="submit" value="Actualizar">
        </p>
        <br><br>
        </form>
    {% endif %}


    {% if form_errors %}
        <h2 style="color: red;" >Errores:</h2>
        {{form_errors}}
    {% endif %}


    {% if message %}
    <div class="alert alert-success" role="alert">{{message}}</div>
    {% endif %}





{% endblock %}